# Book settings
# Learn more at https://jupyterbook.org/customize/config.html
title: 《NLP 从零到专家》
author: 张春阳
logo: _static/logo.png
copyright: "2022, CYang, CC-BY-SA 4.0 (materials) & BSD (code)" 
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", "pytorch-sentiment-analysis", "exercise"]

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/CYang828  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)


# More detail https://jupyterbook.org/en/stable/customize/config.html?highlight=powered%20by#configuration-defaults
sphinx:
  extra_extensions: [sphinx_jupyterbook_latex, sphinx_tabs.tabs, sphinx_multitoc_numbering, sphinxext.rediraffe, sphinx_tojupyter, sphinxcontrib.youtube, sphinx.ext.todo, sphinx_exercise, sphinx_togglebutton, sphinxcontrib.bibtex]
  config:
    language: zh
    nb_render_priority:
      html:
      - "application/vnd.jupyter.widget-view+json"
      - "application/javascript"
      - "text/html"
      - "text/latex"
      - "image/svg+xml"
      - "image/png"
      - "image/jpeg"
      - "text/markdown"
      - "text/plain"
      jupyter:
      - "application/vnd.jupyter.widget-view+json"
      - "application/javascript"
      - "text/html"
      - "text/latex"
      - "image/svg+xml"
      - "image/png"
      - "image/jpeg"
      - "text/markdown"
      - "text/plain"
    html_theme: sphinx_book_theme
    html_static_path: ['_static']
    html_theme_options:
      extra_navbar: <img src="http://aimaksen.bslience.cn/wechat.jpg" width="128" height="128"/>
#       use_repository_button: true
      use_issues_button: true
      use_edit_page_button: true
      fontawesome_included: True
      repository_url: https://github.com/CYang828/nlp-is-not-hard

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository